PraireSTEM AR Capstone: customcamera Namespace Reference
customcamera Namespace Reference
Classes
class CameraDefaults
class CustomCamera
Functions
def get_valid_debug ()
def get_valid_resolutions ()
def get_valid_framerate ()
def get_valid_hflip ()
def get_valid_vflip ()
def get_valid_rotation ()
def get_valid_iso ()
def get_valid_brightness ()
def get_valid_contrast ()
def get_valid_saturation ()
def get_valid_stabilization ()
Function Documentation
get_valid_brightness()
def customcamera.get_valid_brightness ()
Static method that defines list of valid brightness values
:return: list of valid brightness values
Referenced by customcamera.CustomCamera.set_brightness().
get_valid_contrast()
def customcamera.get_valid_contrast ()
Static method that defines list of valid contrast values
:return: list of valid contrast values
Referenced by customcamera.CustomCamera.set_contrast().
get_valid_debug()
def customcamera.get_valid_debug ()
Static method that defines list of valid debug values
:return: list of valid debug values
Referenced by customcamera.CustomCamera.set_debug().
get_valid_framerate()
def customcamera.get_valid_framerate ()
Static method that defines list of valid frame rates
:return: list of valid frame rates
Referenced by customcamera.CustomCamera.set_framerate().
get_valid_hflip()
def customcamera.get_valid_hflip ()
Static method that defines list of valid h-flip value
:return: list of valid h-flip values
Referenced by customcamera.CustomCamera.set_hflip().
get_valid_iso()
def customcamera.get_valid_iso ()
Static method that defines list of valid iso values
:return: list of valid iso values
Referenced by customcamera.CustomCamera.set_iso().
get_valid_resolutions()
def customcamera.get_valid_resolutions ()
Static method that defines list of valid resolutions
:return: list of valid resolutions
Referenced by customcamera.CustomCamera.set_resolution().
get_valid_rotation()
def customcamera.get_valid_rotation ()
Static method that defines list of valid rotation values
:return: list of valid rotation values
Referenced by customcamera.CustomCamera.set_rotation().
get_valid_saturation()
def customcamera.get_valid_saturation ()
Static method that defines list of valid saturation values
:return: list of valid saturation values
Referenced by customcamera.CustomCamera.set_saturation().
get_valid_stabilization()
def customcamera.get_valid_stabilization ()
Static method that defines list of valid stabilization values
:return: list of valid stabilization values
Referenced by customcamera.CustomCamera.set_stabilization().
get_valid_vflip()
def customcamera.get_valid_vflip ()
Static method that defines list of valid v-flip value
:return: list of valid v-flip values
Referenced by customcamera.CustomCamera.set_vflip().