PraireSTEM AR Capstone: ec2server Namespace Reference
ec2server Namespace Reference
Classes
class ZMQCommunication
class CustomTimer
Functions
def get_active_connections ()
def find_new_port ()
def add_back_port ()
def thread_available_connections ()
def thread_add_back ()
def thread_timer_free_up (port, zmq)
def establish_connection (connection, ip, port)
def thread_function (new_port, protocol)
Variables
int OFFSET = 10000
int STARTING_PORT = 10000
int AVAILABLE_PORTS = 10000
int INITIALIZE_CONNECTION_PORT = 5050
int GET_AVAILABLE_CONNECTIONS_PORT = 5051
list USED_PORTS = []
connections = dict()
print_lock = threading.Lock()
dict_lock = threading.Lock()
string ec2_host = "ec2-34-201-129-143.compute-1.amazonaws.com"
option_parse = argparse.ArgumentParser(description="Set up of EC2 server")
type
bool
default
False
help
choices
True
str
command_args = vars(option_parse.parse_args())
target
incoming_connection
incoming_address
establish_connection
args
Function Documentation
add_back_port()
def ec2server.add_back_port ()
Looks through ports that have become inactive and moves them back to our available port list
Referenced by thread_add_back().
establish_connection()
def ec2server.establish_connection (connection, ip, port)
For use in separate thread, attempts to intialize a new connection using parameters
:param connection: Connection object from socket library
:param ip: Incoming IP address from where the request originated
:param port: Port that we are attempting to bind this connection to
References establish_connection, find_new_port(), str, and thread_function().
find_new_port()
def ec2server.find_new_port ()
Searches for next available port for when we are looking to create a new connection
:return new_port: Returns the int value of the next available port
References server.int.
Referenced by establish_connection().
get_active_connections()
def ec2server.get_active_connections ()
Gets the currently active connections and formats them as JSON
Used to communicating active connections to Unity
:return ret_list: JSON.dumps the ret_list of active connections, JSON formatted
Referenced by thread_available_connections().
thread_add_back()
def ec2server.thread_add_back ()
For use in separate thread, simple loop for calling add_back_port() to free up inactive connections
References add_back_port().
thread_available_connections()
def ec2server.thread_available_connections ()
For use in separate thread, uses our output socket to send JSON formatted active connections
In our instance, it will be picked up by Unity to create dropdown of feeds
References get_active_connections().
thread_function()
def ec2server.thread_function (new_port, protocol)
For use in a seperate thread, where the magic happens, maintains the connection of our video feed accepting values from the Pi socket and forwards them to the ouput socket
:param new_port: Port that will be used from incoming video feed frames
:param protocol: Protocol we will use to process the video feed and forward to output socket
References str.
Referenced by establish_connection().
thread_timer_free_up()
def ec2server.thread_timer_free_up (port, zmq)
For use in separate thread, is called by CustomTimer when a connection has not been active recently
Marks the connection as inactive for cleanup, attempts to force close connection if ZMQ object is passed
:param port: The port of the connection we are currently looking at
:param zmq: In certain situations, a ZMQ object will be forwarded so we can attempt to force close
Variable Documentation
args
ec2server.args
AVAILABLE_PORTS
list ec2server.AVAILABLE_PORTS = 10000
bool
ec2server.bool
choices
ec2server.choices
command_args
ec2server.command_args = vars(option_parse.parse_args())
connections
ec2server.connections = dict()
default
ec2server.default
dict_lock
ec2server.dict_lock = threading.Lock()
ec2_host
string ec2server.ec2_host = "ec2-34-201-129-143.compute-1.amazonaws.com"
establish_connection
ec2server.establish_connection
Referenced by establish_connection().
False
ec2server.False
GET_AVAILABLE_CONNECTIONS_PORT
int ec2server.GET_AVAILABLE_CONNECTIONS_PORT = 5051
help
ec2server.help
incoming_address
ec2server.incoming_address
incoming_connection
ec2server.incoming_connection
INITIALIZE_CONNECTION_PORT
int ec2server.INITIALIZE_CONNECTION_PORT = 5050
OFFSET
int ec2server.OFFSET = 10000
option_parse
ec2server.option_parse = argparse.ArgumentParser(description="Set up of EC2 server")
print_lock
ec2server.print_lock = threading.Lock()
STARTING_PORT
int ec2server.STARTING_PORT = 10000
str
ec2server.str
Referenced by establish_connection(), and thread_function().
target
ec2server.target
True
ec2server.True
type
ec2server.type
USED_PORTS
list ec2server.USED_PORTS = []